// Using public URLs for images to avoid build issues
export const food_items = [
  { id: 1,  food_name: "Pancakes",             food_category: "breakfast",   food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image1.avif",  price: 499 },
  { id: 2,  food_name: "Chicken Soup",         food_category: "soups",       food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image2.avif",  price: 399 },
  { id: 3,  food_name: "Minestrone Soup",      food_category: "soups",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image3.avif",  price: 349 },
  { id: 4,  food_name: "Spaghetti Carbonara",  food_category: "pasta",       food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image4.avif",  price: 999 },
  { id: 5,  food_name: "Veg Alfredo Pasta",    food_category: "pasta",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image5.avif",  price: 899 },
  { id: 6,  food_name: "Chicken Alfredo Pasta",food_category: "pasta",       food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image6.avif",  price: 1099 },
  { id: 7,  food_name: "Paneer Butter Masala", food_category: "main_course", food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image7.avif",  price: 799 },
  { id: 8,  food_name: "Chicken Biryani",      food_category: "main_course", food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image8.avif",  price: 1199 },
  { id: 9,  food_name: "Margherita Pizza",     food_category: "pizza",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image9.avif",  price: 649 },
  { id: 10, food_name: "Pepperoni Pizza",      food_category: "pizza",       food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image10.avif", price: 749 },
  { id: 11, food_name: "Veggie Burger",        food_category: "burger",      food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image11.avif", price: 499 },
  { id: 12, food_name: "Chicken Burger",       food_category: "burger",      food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image12.avif", price: 599 },
  { id: 13, food_name: "Tomato Soup",          food_category: "soups",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image13.avif", price: 299 },
  { id: 14, food_name: "Egg Sandwich",         food_category: "breakfast",   food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image14.webp", price: 349 },
  { id: 15, food_name: "Mushroom Soup",        food_category: "soups",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image15.avif", price: 349 },
  { id: 16, food_name: "Chicken Tikka Masala", food_category: "main_course", food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image16.avif", price: 1199 },
  { id: 17, food_name: "Cheese Omelette",      food_category: "breakfast",   food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image17.avif", price: 399 },
  { id: 18, food_name: "Fettuccine Alfredo",   food_category: "pasta",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image18.avif", price: 949 },
  { id: 19, food_name: "Garlic Bread",         food_category: "pizza",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image19.avif", price: 299 },
  { id: 20, food_name: "Fish and Chips",       food_category: "main_course", food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image20.avif", price: 1099 },
  { id: 21, food_name: "Hash Browns",          food_category: "breakfast",   food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image21.avif", price: 249 },
  { id: 22, food_name: "Vegetable Soup",       food_category: "soups",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image22.avif", price: 329 },
  { id: 23, food_name: "Egg Fried Rice",       food_category: "main_course", food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image23.avif", price: 599 },
  { id: 24, food_name: "Hawaiian Pizza",       food_category: "pizza",       food_type: "non_veg",  food_quantity: 1, food_image: "/src/assets/image24.avif", price: 799 },
  { id: 25, food_name: "Pasta Primavera",      food_category: "pasta",       food_type: "veg",      food_quantity: 1, food_image: "/src/assets/image25.avif", price: 899 }
];